version: '3.8'

services:
  db:
    image: postgres
    container_name: chat_psql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
